name: tictactoe_flutter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.0.3
  json_annotation: ^4.9.0
  riverpod_annotation: ^3.0.3
  shared_preferences: ^2.5.3
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3
  json_serializable: ^6.11.2
  build_runner: ^2.10.4
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true
