name: tictactoe_flutter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.0.3
  json_annotation: ^4.9.0
  logger: ^2.6.2
  riverpod_annotation: ^3.0.3
  shared_preferences: ^2.5.3
  simple_animations: ^5.2.0
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3
  json_serializable: ^6.11.2
  build_runner: ^2.10.4
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/nunito/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/nunito/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/nunito/Nunito-BlackItalic.ttf
          weight: 900
          style: italic


  
